##################################################
# Test Name: Header Regex Value Match
# Test Number: 4.2.3
# Test Description:
#   - Route X-frontend-app header value cluster-1 to cluster-1 frontend
#   - Route X-frontend-app header value cluster-* to cluster-2 frontend
##################################################
apiVersion: networking.mesh.gloo.solo.io/v1
kind: VirtualMesh
metadata:
  name: virtual-mesh
  namespace: gloo-mesh
spec:
  federation:                            # Enable automatic federation of all services to all clusters
    selectors:
      - {}
  meshes:
    - name: istiod-istio-system-cluster-1
      namespace: gloo-mesh
    - name: istiod-istio-system-cluster-2
      namespace: gloo-mesh
---
apiVersion: networking.enterprise.mesh.gloo.solo.io/v1beta1
kind: VirtualGateway
metadata:
  name: ingress
  namespace: gloo-mesh
spec:
  ingressGatewaySelectors:
  - portName: http2                      # match on port name http2
    destinationSelectors:
    - kubeServiceMatcher:
        labels:
          istio: ingressgateway          # select all gateways with istio=ingressgateway label
        namespaces:
        - istio-system                   # only include istio-system namespace
  connectionHandlers:
  - http:
      routeConfig:
      - virtualHost:
          domains:
          - "api.solo.io"
          routes:
          - matchers:                    # route to specific cluster
            - headers:
              - name: X-frontend-app
                value: cluster-1
            name: frontend-cluster-1
            routeAction:
              destinations:
              - kubeService:
                  clusterName: cluster-1
                  name: frontend
                  namespace: app
                  port: 8080
          - matchers:                    # anything other than cluster-1 be routed to cluster-2
            - headers:
              - name: X-frontend-app
                value: cluster-.*
                regex: true              # enable regex support
            name: frontend-cluster-2
            routeAction:
              destinations:
              - kubeService:
                  clusterName: cluster-2
                  name: frontend
                  namespace: app
                  port: 8080