##################################################
# Test Name: Traffic Policy Selecting VirtualDestination as Destination
# Test Number: 1.2.3
# Test Description:
#   - Setting request timeouts for requests bound for a VirtualDestination by labels
##################################################
apiVersion: networking.mesh.gloo.solo.io/v1
kind: VirtualMesh
metadata:
  name: virtual-mesh
  namespace: gloo-mesh
spec:
  federation:
    selectors:
      - { }
  meshes:
    - name: istiod-istio-system-cluster-2
      namespace: gloo-mesh
    - name: istiod-istio-system-cluster-1
      namespace: gloo-mesh
---
apiVersion: networking.enterprise.mesh.gloo.solo.io/v1beta1
kind: VirtualDestination
metadata:
  name: frontend
  namespace: gloo-mesh
  labels:
    virtual-destination: frontend        # used for selection by TrafficPolicy destinationSelector
spec:
  port:
    number: 8080                         # matches frontend port
    protocol: http
    targetNumber: 8080                   # matches frontend service port
    destinationSelectors:                # all frontend applications in all clusters
      - kubeServiceMatcher:
          labels:
            app: frontend
  virtualMesh:                           # apply to virtual-mesh
    name: virtual-mesh
    namespace: gloo-mesh
---
apiVersion: networking.mesh.gloo.solo.io/v1
kind: TrafficPolicy
metadata:
  namespace: gloo-mesh
  name: frontend-timeout
spec:
  # sourceSelector:                      # source selector omitted means "apply to anything calling destination"
  destinationSelector:
    - virtualDestinationMatcher:         # select VirtualDestination by label
        labels:
          virtual-destination: frontend  # matches label in VirtualDestination
        namespaces: 
        - gloo-mesh
  policy:
    requestTimeout: 1s                   # request timeout of 1s