##################################################
# Test Name: Sort RouteTables By Specificity
# Test Number: 8.4
# API Version: 2
# Test Description:
#   - After processing all routes, including additional route tables delegated to, the resulting routes are sorted by specificity to reduce the chance that a more specific route will be short-circuited by a general route. Matchers with exact path matchers are considered more specific than regex path patchers, which are more specific than prefix path matchers. 
#   - Matchers of the same type are sorted by length of the path in descending order. 
#   - Only the most specific matcher on each route is used.
##################################################
apiVersion: admin.gloo.solo.io/v2
kind: RootTrustPolicy
metadata:
  name: auto-mtls
  namespace: gloo-mesh
spec:
  applyToMeshes:
    - name: istiod-istio-system-cluster-1
      namespace: gloo-mesh
    - name: istiod-istio-system-cluster-2
      namespace: gloo-mesh
  config:
    rootCertificateAuthority:            # auto generate ca certificates for each istio mesh
      generated:  {}
---
apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: admin                           # workspace for admin config
  namespace: gloo-mesh
spec:
  workloadClusters:
   - selector:
      namespaces:
        - name: istio-system
---
apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: admin-settings
  namespace: admin                       # workspace settings must exist in workspace namespace
spec:
 imports:                                # import setting from cluster-1
 - name: cluster-1
 exportTo:                               # export to cluster-1 it can use ingressgateway
 - name: cluster-1
---
apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: cluster-1                        # workspace for cluster-1 config
  namespace: gloo-mesh
spec:
  workloadClusters:
   - name: cluster-1
---
apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: cluster-1-settings
  namespace: cluster-1                   # workspace settings must exist in workspace namespace
spec:
 exportTo:                               # export to admin workspace
 - name: admin
---
apiVersion: networking.gloo.solo.io/v2   # virtual gateway owned by admin workspace
kind: VirtualGateway
metadata:
  name: ingress                          # applies to all gateways in the mesh 
  namespace: admin
spec:
  listeners:
    - port:
        name: http2                      # apply configuration to ingress gateways http port
---
apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: ignress-routes
  namespace: admin
spec:
  hosts:
    - 'frontend.solo.io'
  virtualGateways:
    - name: ingress
  http:
  - name: cluster-1-routes
    delegate:                            # delegate frontend.solo.io to route tables with label gateway=ingress
      sortMethod: ROUTE_SPECIFICITY
      routeTables:
      - selector:
          gateway: ingress
---
apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: frontend
  namespace: cluster-1
  labels:
    gateway: ingress
spec:
  hosts:
    - 'frontend.solo.io'
  virtualGateways:
    - name: ingress
      workspace: admin
  http:
  - name: frontend
    matchers:
    - name: frontend
      uri:
        prefix: /frontend
    forwardTo:
      destinations:
      - name: frontend
        namespace: app
        port:
          number: 8080
---
apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: frontend
  namespace: cluster-1
  labels:
    gateway: ingress
spec:
  hosts:
    - 'frontend.solo.io'
  virtualGateways:
    - name: ingress
      workspace: admin
  http:
  - name: frontend
    matchers:
    - name: frontend
      uri:
        prefix: /frontend/cluster-2
    forwardTo:
      destinations:
      - name: frontend
        namespace: app
        port:
          number: 8080