apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: ingress
spec:
  profile: minimal
  components:
    pilot:
      k8s:
        env:
        # Disable selecting workload entries for local service routing, so that Kubernetes 
        # will not automatically match services to workload entries with matching selector labels.
        # Required for Gloo Mesh VirtualDestination functionality.
        # For more info, see https://istio.io/latest/docs/reference/commands/pilot-discovery/
        - name: PILOT_ENABLE_K8S_SELECT_WORKLOAD_ENTRIES
          value: "false"
        # Autoregistration allows the istiod control plane to create the workload 
        # entries associated with your VM automatically after the VM is onboarded.
        - name: PILOT_ENABLE_WORKLOAD_ENTRY_AUTOREGISTRATION
          value: "true"
        # Enable automatic health checks for the VM workload entry
        - name: PILOT_ENABLE_WORKLOAD_ENTRY_HEALTHCHECKS
          value: "true"
        - name: TELEMETRY_USE_NATIVE_STATS
          value: "true"
    ingressGateways:
      - name: istio-eastwestgateway
        # Deploy to the east-west gateway namespace.
        namespace: istio-eastwest
        enabled: true
        label:
          # Set a unique label for the gateway.
          # Required to ensure Gateways can select this workload.
          istio: eastwestgateway
          app: istio-eastwestgateway
          # Matches spec.values.global.network in the istiod deployment
          topology.istio.io/network: $CLUSTER_NAME
        k8s:
          serviceAnnotations:
            cloud.google.com/l4-rbs: "enabled"
          strategy:
            rollingUpdate:
              maxSurge: 100%
              maxUnavailable: 25%
          resources:
            limits:
              cpu: 2000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 40Mi
          service:
            type: LoadBalancer
            # Required to onboard VMs
            type: LoadBalancer
            # Default ports
            ports:
              # Port for health checks on path /healthz/ready.
              # For AWS ELBs, this port must be listed first.
              - port: 15021
                targetPort: 15021
                name: status-port
              # Main HTTPS port for east-west ISTIO_MUTUAL connection.
              - port: 443
                targetPort: 8443
                name: https
              # Port for multicluster mTLS passthrough.
              # Required for Gloo Mesh east-west routing.
              - port: 15443
                targetPort: 15443
                # Gloo Mesh looks for this default name 'tls' on a gateway
                name: tls
              # SPIRE server port
              - name: tls-spire
                port: 8081
                protocol: TCP
                targetPort: 8081
              # Istiod port
              - name: tls-istiod
                port: 15012
                protocol: TCP
                targetPort: 15012
              # Gloo OpenTelemetry port
              - name: tls-otel
                port: 4317
                protocol: TCP
                targetPort: 4317
              - name: grpc-cacert
                port: 31338
                protocol: TCP
                targetPort: 31338
              - name: grpc-ew-bootstrap
                port: 31339
                protocol: TCP
                targetPort: 31339
  values:
    telemetry:
      enabled: false
      v2:
        enabled: true
        metadataExchange:
          wasmEnabled: false
        prometheus:
          enabled: true
          wasmEnabled: false
        stackdriver:
          configOverride: {}
          enabled: false
          logging: false
          monitoring: false
          topology: false
    gateways:
      istio-ingressgateway:
        # Enable gateway injection
        injectionTemplate: gateway
      istio-egressgateway:
        # Enable gateway injection
        injectionTemplate: gateway
    global:
      # Required for connecting VirtualMachines to the mesh
      network: $CLUSTER_NAME
      # Required for annotating Istio metrics with the cluster name.
      # Must match the trustDomain
      multiCluster:
        clusterName: $CLUSTER_NAME
  meshConfig:
    defaultConfig:
      proxyStatsMatcher:
        inclusionRegexps:
          - ".*"
      proxyMetadata:
        # For known hosts, enable the Istio agent to handle DNS requests 
        # for any custom ServiceEntry, such as non-Kubernetes services.
        # Unknown hosts are automatically resolved using upstream DNS servers
        # in resolv.conf (for proxy-dns)
        ISTIO_META_DNS_CAPTURE: "true"
        # Enable automatic address allocation
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"