apiVersion: admin.gloo.solo.io/v2
kind: IstioLifecycleManager
metadata:
  name: istiod-control-plane
  namespace: gloo-mesh
spec:
  installations:
      # The revision for this installation, such as 1-18-3.
      # This MUST be different than the revision that your existing Istio installation uses.
    - revision: $REVISION
      # List all workload clusters to install Istio into
      clusters:
      - name: $REMOTE_CLUSTER1
        # Set to false to ensure the spec for this revision is not yet the active control pane in the cluster
        defaultRevision: false
      - name: $REMOTE_CLUSTER2
        defaultRevision: false
      istioOperatorSpec:
        # Only the control plane components are installed
        # (https://istio.io/latest/docs/setup/additional-setup/config-profiles/)
        profile: minimal
        # Solo.io Istio distribution repository; required for Solo Istio.
        # You get the repo key from your Solo Account Representative.
        hub: $REPO
        # Any Solo Istio tag
        tag: $ISTIO_IMAGE
        namespace: istio-system
        # Mesh configuration
        meshConfig:
          # Enable access logging only if using.
          accessLogFile: /dev/stdout
          # Encoding for the proxy access log (TEXT or JSON). Default value is TEXT.
          accessLogEncoding: JSON
          # Enable span tracing only if using.
          enableTracing: true
          defaultConfig:
            # Wait for the istio-proxy to start before starting application pods
            holdApplicationUntilProxyStarts: true
            proxyMetadata:
              # For known hosts, enable the Istio agent to handle DNS requests for any custom ServiceEntry, such as non-Kubernetes services.
              # Unknown hosts are automatically resolved using upstream DNS servers in resolv.conf (for proxy-dns)
              ISTIO_META_DNS_CAPTURE: "true"
          # Set the default behavior of the sidecar for handling outbound traffic
          # from the application
          outboundTrafficPolicy:
            mode: ALLOW_ANY
          # The administrative root namespace for Istio configuration
          rootNamespace: istio-system
          # Set to the cluster name by default.
          trustDomain: ${CLUSTER_NAME}
        # Traffic management
        components:
          # Disable gateways deployments, which are deployed in separate resources
          ingressGateways:
          - name: istio-ingressgateway
            enabled: false
          - name: istio-eastwestgateway
            enabled: false
          egressGateways:
          - name: istio-egressgateway
            enabled: false
          pilot:
            k8s:
              env:
                # Disable selecting workload entries for local service routing, so that Kubernetes 
                # will not automatically match services to workload entries with matching selector labels.
                # Required for Gloo Mesh VirtualDestination functionality.
                # For more info, see https://istio.io/latest/docs/reference/commands/pilot-discovery/
                - name: PILOT_ENABLE_K8S_SELECT_WORKLOAD_ENTRIES
                  value: "false"
      # Helm values overrides
      values:
        global:
          multiCluster:
            # Set to the cluster name by default.
            clusterName: $CLUSTER_NAME