##################################################
# Test Name: Traffic Policy Mirroring
# Test Number: 9.1
# Test Description:
#   - Mirror traffic from one application to another
##################################################
apiVersion: networking.mesh.gloo.solo.io/v1
kind: VirtualMesh
metadata:
  name: virtual-mesh
  namespace: gloo-mesh
spec:
  federation:
    selectors:
      - { }
  meshes:
    - name: istiod-istio-system-cluster-2
      namespace: gloo-mesh
    - name: istiod-istio-system-cluster-1
      namespace: gloo-mesh
---
apiVersion: networking.mesh.gloo.solo.io/v1
kind: TrafficPolicy
metadata:
  namespace: gloo-mesh
  name: frontend
spec:
  # sourceSelector:                      # source selector omitted means "apply to anything calling destination"
  destinationSelector:
    - kubeServiceMatcher:                # kubeServiceMatcher is a select many services by labels/namespaces/clusters using AND notation
        labels:
          app: frontend                  # applications with app=frontend label
  policy:
    mirror:                              # mirror 50% traffic from cluster-1 frontend to cluster-2
      port: 8080
      percentage: 50
      kubeService:
        clusterName: cluster-2
        name: frontend
        namespace: app