##################################################
# Test Name: Virtual Destination Port Selection
# Test Number: 2.1
# Test Description:
#   - Define custom hostname with custom port http://frontend.solo.internal:15000
##################################################
apiVersion: networking.mesh.gloo.solo.io/v1
kind: VirtualMesh
metadata:
  name: virtual-mesh
  namespace: gloo-mesh
spec:
  federation:
    selectors:
      - { }
  meshes:
    - name: istiod-istio-system-cluster-2
      namespace: gloo-mesh
    - name: istiod-istio-system-cluster-1
      namespace: gloo-mesh
---
apiVersion: networking.enterprise.mesh.gloo.solo.io/v1beta1
kind: VirtualDestination
metadata:
  name: frontend
  namespace: gloo-mesh
spec:
  hostname: frontend.solo.internal       # in mesh services can reach frontend by this hostname
  port:
    number: 15000                        # Port that in mesh services must use
    protocol: http
    targetNumber: 8080                   # matches frontend service port
  localized:
    destinationSelectors:                # all frontend applications in all clusters
      - kubeServiceMatcher:
          labels:
            app: frontend
  virtualMesh:                           # apply to virtual-mesh
    name: virtual-mesh
    namespace: gloo-mesh