##################################################
# Test Name: Namespace Based Delegation
# Test Number: 8.1
# Test Description:
#   - Delegate cluster1.solo.io to cluster1 RouteTable
#   - Delegate cluster2.solo.io to cluster2 RouteTable
##################################################
apiVersion: v1
kind: Namespace
metadata:
  name: virtual-hosts
---
apiVersion: v1
kind: Namespace
metadata:
  name: cluster1-routes
---
apiVersion: v1
kind: Namespace
metadata:
  name: cluster2-routes

---
apiVersion: networking.mesh.gloo.solo.io/v1
kind: VirtualMesh
metadata:
  name: virtual-mesh
  namespace: gloo-mesh
spec:
  federation:                            # Enable automatic federation of all services to all clusters
    selectors:
      - {}
  meshes:
    - name: istiod-istio-system-cluster1
      namespace: gloo-mesh
    - name: istiod-istio-system-cluster2
      namespace: gloo-mesh
---
apiVersion: networking.enterprise.mesh.gloo.solo.io/v1beta1
kind: VirtualGateway
metadata:
  name: ingress
  namespace: gloo-mesh
spec:
  ingressGatewaySelectors:
  - portName: http2                      # match on port name http2
    destinationSelectors:
    - kubeServiceMatcher:
        labels:
          istio: ingressgateway          # select all gateways with istio=ingressgateway label
        namespaces:
        - istio-system                   # only include istio-system namespace
  connectionHandlers:
  - http:
      routeConfig:
      - virtualHostSelector:             # select VirtualHost based in the virtual-hosts namespace
          namespaces:
          - virtual-hosts
---
apiVersion: networking.enterprise.mesh.gloo.solo.io/v1beta1
kind: VirtualHost
metadata:
  name: cluster1
  namespace: virtual-hosts
  labels:
    gateway: ingress
spec:
  domains:
  - cluster1.solo.io
  routes:
  - delegateAction:                      # domain cluster1.solo.io applies to RouteTables in the cluster1-routes namespace
      selector:
        namespaces:
        - cluster1-routes
---
apiVersion: networking.enterprise.mesh.gloo.solo.io/v1beta1
kind: VirtualHost
metadata:
  name: cluster2
  namespace: virtual-hosts
  labels:
    gateway: ingress
spec:
  domains:
  - cluster2.solo.io
  routes:
  - delegateAction:                      # domain cluster1.solo.io applies to RouteTables in the cluster2-routes namespace
      selector:
        namespaces:
        - cluster2-routes
---
apiVersion: networking.enterprise.mesh.gloo.solo.io/v1beta1
kind: RouteTable
metadata:
  name: frontend
  namespace: cluster1-routes            # matches the namespace selector in cluster1 VirtualHost
spec:
  routes:
  - matchers:
    - uri:
        prefix: /frontend                # only match on cluster1.solo.io/frontend
    name: frontend
    routeAction:
      destinations:
      - kubeService:                     # route requests to cluster1 frontend application
          clusterName: cluster1
          name: frontend
          namespace: app
          port: 8080
---
apiVersion: networking.enterprise.mesh.gloo.solo.io/v1beta1
kind: RouteTable
metadata:
  name: frontend
  namespace: cluster2-routes            # matches the namespace selector in cluster2 VirtualHost
spec:
  routes:
  - matchers:
    - uri:
        prefix: /frontend                # only match on cluster2.solo.io/frontend
    name: frontend
    routeAction:
      destinations:
      - kubeService:                     # route requests to cluster2 frontend application
          clusterName: cluster2
          name: frontend
          namespace: app
          port: 8080