##################################################
# Test Name: Suffix Path Route Matching
# Test Number: 4.1.4
# Test Description:
#   - Route /.*/frontend to frontend application
# Issues
#  - https://github.com/solo-io/gloo-mesh-enterprise/issues/2053
##################################################
# establish a listener on the ingress gateway
apiVersion: networking.gloo.solo.io/v2
kind: VirtualGateway
metadata:
  name: ingress
  namespace: global
spec:
  workloads:
    - selector:
        istio: ingressgateway
  listeners:
    - port:
        number: 80
      http: {}
---
apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: frontend
  namespace: global
spec:
  hosts:
    - 'api.solo.io'
  virtualGateways:
    - name: ingress
  http:
  - matchers:
    - uri:
        suffix: /frontend
    forwardTo:
      destinations:
      - ref:
          name: frontend
          namespace: {{.EchoContext.AppNamespace.Name}}
          cluster: cluster-1
        port:
          number: 8090
---