##################################################
# Test Name: Virtual Destination Mesh Selection
# Test Number: 3.1
# Test Description:
#   - Set VirtualDestination to only be available in cluster-1
#   - Since the VirtualDestination references a backend in cluster-2 itll actually also be available in cluster-2
##################################################
apiVersion: networking.mesh.gloo.solo.io/v1
kind: VirtualMesh
metadata:
  name: virtual-mesh
  namespace: gloo-mesh
spec:
  federation:
    selectors:
      - { }
  meshes:
    - name: istiod-istio-system-cluster-2
      namespace: gloo-mesh
    - name: istiod-istio-system-cluster-1
      namespace: gloo-mesh
---
apiVersion: networking.enterprise.mesh.gloo.solo.io/v1beta1
kind: VirtualDestination
metadata:
  name: frontend
  namespace: gloo-mesh
spec:
  hostname: frontend.solo.internal       # in mesh services can reach frontend by this hostname
  port:
    number: 8080                        # Port that in mesh services must use
    protocol: http
    targetNumber: 8080                   # matches frontend service port
  localized:
    destinationSelectors:                # all frontend applications in all clusters
      - kubeServiceMatcher:
          labels:
            app: frontend
          clusters:
            - cluster-2
  meshList:                              # apply to selected meshes
    meshes:
      - name: istiod-istio-system-cluster-1
        namespace: gloo-mesh