apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: production-istio
  namespace: istio-system
spec:
  # Only the control plane components are installed (https://istio.io/latest/docs/setup/additional-setup/config-profiles/)
  profile: minimal
  # Solo.io Istio distribution repository; required for Gloo Mesh Istio. You get the repo key from your Solo Account Representative.
  hub: $REPO
  # Any Solo.io Gloo Mesh Istio tag
  tag: $ISTIO_IMAGE
  # Istio revision to create resources with
  revision: $REVISION

  # Mesh configuration
  meshConfig:
    # Enable access logging only if using.
    #accessLogFile: /dev/stdout
    # Encoding for the proxy access log (TEXT or JSON). Default value is TEXT.
    #accessLogEncoding: JSON
    # Enable span tracing only if using.
    #enableTracing: true

    defaultConfig:
      # Wait for the istio-proxy to start before starting application pods
      holdApplicationUntilProxyStarts: true
      # Enable Gloo Mesh metrics service. Required for Gloo Mesh UI
      envoyMetricsService:
        address: gloo-mesh-agent.gloo-mesh:9977
      # Enable Gloo Mesh accesslog service. Required for Gloo Mesh Access Logging
      envoyAccessLogService:
        address: gloo-mesh-agent.gloo-mesh:9977
      proxyMetadata:
        # For known hosts, enable Istio agent to handle DNS requests for any custom ServiceEntry, such as non-Kubernetes services.
        # Unknown hosts are automatically resolved using upstream DNS servers in resolv.conf (for proxy-dns)
        ISTIO_META_DNS_CAPTURE: "true"
        # Enable automatic address allocation within envoy to route to non-Kubernetes services.
        # Useful for external services where the IP address may change by creating an internal stable IP address that represents the external host.
        # For more info, see https://istio.io/latest/docs/ops/configuration/traffic-management/dns-proxy/
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"

    # Set the default behavior of the sidecar for handling outbound traffic from the application
    outboundTrafficPolicy:
      mode: ALLOW_ANY
    # The trust root of a system, which is the name of the cluster that corresponds with the CA certificate CommonName identity
    trustDomain: $CLUSTER_NAME
    # The administrative root namespace for Istio configuration
    rootNamespace: istio-config

  # Traffic management
  components:
    base:
      enabled: true
    pilot:
      enabled: true
      k8s:
        # Recommended to be >1 in production
        replicaCount: 2
        # The Istio load tests mesh consists of 1000 services and 2000 sidecars
        # with 70,000 mesh-wide requests per second and Istiod used 1 vCPU and 1.5 GB of memory.
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        strategy:
          rollingUpdate:
            maxSurge: 100%
            maxUnavailable: 25%
        # Recommended to scale istiod under load
        hpaSpec:
          maxReplicas: 5
          minReplicas: 2
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            # matches the format istiod-<revision_label>
            name: istiod-$REVISION
          metrics:
            - resource:
                name: cpu
              type: Resource
        env:
          # Disable selecting workload entries for local service routing, so that Kubernetes 
          # will not automatically match services to workload entries with matching selector labels.
          # Required for Gloo Mesh VirtualDestination functionality.
          # For more info, see https://istio.io/latest/docs/reference/commands/pilot-discovery/
          - name: PILOT_ENABLE_K8S_SELECT_WORKLOAD_ENTRIES
            value: "false"
          # Skip the validation step for mTLS within the cluster.
          # This approach is not recommended if you integrated Istio with your own CA,
          # but is useful for PoCs or demos in which you use self-signed certificates.
          - name: PILOT_SKIP_VALIDATE_TRUST_DOMAIN
            value: "true"
    # Openshift requires the Istio CNI feature to be enabled
    cni:
      enabled: true
      namespace: kube-system
      k8s:
        overlays:
          - kind: DaemonSet
            name: istio-cni-node
            patches:
              - path: spec.template.spec.containers[0].securityContext.privileged
                value: true

    # Istio Gateway feature
    # Disable gateways deployments, which are deployed in separate IstioOperator configurations
    ingressGateways:
    - name: istio-ingressgateway
      enabled: false
    - name: istio-eastwestgateway
      enabled: false
    egressGateways:
    - name: istio-egressgateway
      enabled: false

  # Helm values overrides
  values:
    # CNI options for OpenShift
    cni:
      cniBinDir: /var/lib/cni/bin
      cniConfDir: /etc/cni/multus/net.d
      chained: false
      cniConfFileName: "istio-cni.conf"
      excludeNamespaces:
       - istio-system
       - kube-system
      logLevel: info
    sidecarInjectorWebhook:
      injectedAnnotations:
        k8s.v1.cni.cncf.io/networks: istio-cni
    # https://istio.io/v1.5/docs/reference/config/installation-options/#global-options
    global:
      # Required for connecting VirtualMachines to the mesh
      network: $CLUSTER_NAME
      # Required for annotating Istio metrics with the cluster name.
      # Must match the trustDomain
      multiCluster:
        clusterName: $CLUSTER_NAME
      # Sidecar resource settings
      # proxy:
      # The Istio load tests mesh consists of 1000 services and 2000 sidecars with 70,000 mesh-wide 
      # requests per second and istio-proxy used 0.35 vCPU and 40 MB memory per 1000 requests per second.
      #   resources:
      #     requests:
      #       cpu: 100m
      #       memory: 128Mi
      #     limits: 
      #       cpu: 2000m
      #       memory: 1024Mi
      #   logLevel: warning
