##################################################
# Test Name: Traffic Policy fault injection
# Test Number: 6.2
# Test Description:
#   - Abort requests and return 401 status
##################################################
apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: global                           # workspace contains all connected services
  namespace: gloo-mesh
spec:
  workloadClusters:                      # select all clusters and namespaces
  - name: "*"
    namespaces:
    - name: "*"
---
apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: settings
  namespace: global
spec:
 {}
---
apiVersion: resilience.policy.gloo.solo.io/v2
kind: FaultInjectionPolicy
metadata:
  name: fault-injection
  namespace: global
spec:
  applyToRoutes:
  - withDestinations:
      selector:
        labels:
          app: frontend
  config:
    abort:
      httpStatus: 401
      percentage: 100