##################################################
# Test Name: Traffic Policy to tune connection pool settings
# Test Number: 4.1.7
# Test Description:
#   - Setting useClientProtocol - client protocol will be preserved while initiating connection to backend
##################################################
apiVersion: networking.mesh.gloo.solo.io/v1
kind: VirtualMesh
metadata:
  name: virtual-mesh
  namespace: gloo-mesh
spec:
  federation:
    selectors:
      - { }
  meshes:
    - name: istiod-istio-system-cluster-2
      namespace: gloo-mesh
    - name: istiod-istio-system-cluster-1
      namespace: gloo-mesh
---
apiVersion: networking.mesh.gloo.solo.io/v1
kind: TrafficPolicy
metadata:
  namespace: gloo-mesh
  name: frontend
spec:
  # destinationSelector:                 # destination selector omitted means "apply to all destinations"
  sourceSelector:                        # select any application with the label app=frontend
    - kubeServiceMatcher:
        labels:
          app: frontend
  policy:
    connectionPoolSettings:
      http:
        useClientProtocol: true         # Client protocol will be preserved while initiating connection to backend