##################################################
# Test Name: Virtual Destination Port Selection
# Test Number: 2.1
# Test Description:
#   - Define custom hostname with custom port http://frontend.solo.internal:15500
# Issues
# - https://github.com/solo-io/gloo-mesh-enterprise/issues/2080
##################################################
apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: global                           # workspace contains all connected services
  namespace: gloo-mesh
spec:
  workloadClusters:                      # select all clusters and namespaces
  - name: "*"
    namespaces:
    - name: "*"
---
apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: settings
  namespace: global
spec:
 {}
---
apiVersion: networking.gloo.solo.io/v2
kind: VirtualDestination
metadata:
  name: frontend
  namespace: global
spec:
  hosts:
    - frontend.solo.io
  selectors:
    labels:
      app: frontend
    cluster: cluster-2
  ports:
  - name: http
---
#apiVersion: networking.enterprise.mesh.gloo.solo.io/v1beta1
#kind: VirtualDestination
#metadata:
#  name: frontend
#  namespace: gloo-mesh
#spec:
#  hostname: frontend.solo.internal       # in mesh services can reach frontend by this hostname
#  port:
#    number: 15500                        # Port that in mesh services must use
#    protocol: http
#    targetNumber: 8090                   # matches frontend service port
#  localized:
#    destinationSelectors:                # all frontend applications in all clusters
#      - kubeServiceMatcher:
#          labels:
#            app: frontend
#          clusters:
#            - cluster-2
#  virtualMesh:                           # apply to virtual-mesh
#    name: virtual-mesh
#    namespace: gloo-mesh