apiVersion: admin.gloo.solo.io/v2
kind: GatewayLifecycleManager
metadata:
  name: istio-eastwestgateway
  namespace: gloo-mesh
spec:
  installations:
  # The revision for this installation, such as 1-18-3
  - gatewayRevision: $REVISION
    # List all workload clusters to install Istio into
    clusters:
    - name: $REMOTE_CLUSTER1
      # If set to true, the spec for this revision is applied in the cluster
      activeGateway: true
    - name: $REMOTE_CLUSTER2
      activeGateway: true
    istioOperatorSpec:
      # No control plane components are installed
      profile: empty
      # Solo.io Istio distribution repository; required for Solo Istio.
      # You get the repo key from your Solo Account Representative.
      hub: $REPO
      # The Solo Istio version
      tag: $ISTIO_IMAGE
      components:
        ingressGateways:
        # Enable the default east-west gateway
        - name: istio-eastwestgateway
          # Deployed to gloo-mesh-gateways by default
          namespace: gloo-mesh-gateways
          enabled: true
          label:
            # Set a unique label for the gateway. This is required to
            # ensure Gateways can select this workload.
            istio: eastwestgateway
            app: istio-eastwestgateway
          k8s:
            env:
              # 'sni-dnat' enables AUTO_PASSTHROUGH mode for east-west communication through the gateway.
              # The default value ('standard') does not set up a passthrough cluster.
              # Required for multi-cluster communication and to preserve SNI.
              - name: ISTIO_META_ROUTER_MODE
                value: "sni-dnat"
            service:
              type: LoadBalancer
              selector:
                istio: eastwestgateway
              # Default ports
              ports:
                # Port for health checks on path /healthz/ready.
                # For AWS ELBs, this port must be listed first.
                - name: status-port
                  port: 15021
                  targetPort: 15021
                # Port for multicluster mTLS passthrough
                # Gloo looks for this default name 'tls' on a gateway
                # Required for Gloo east/west routing
                - name: tls
                  port: 15443
                  targetPort: 15443
                    