apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-v2
  namespace: app
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: v2
  template:
    metadata:
      labels:
        app: frontend
        version: v2
    spec:
      serviceAccountName: frontend    
      containers:
      - name: frontend
        image: ghcr.io/nmnellis/fake-service:v2
        ports:
        - containerPort: 8080
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:8080"
        - name: "NAME"
          value: "frontend-v2"
        - name: "MESSAGE"
          value: "Hello From frontend V2 (call /ui for service graph)"
