##################################################
# Test Name: Service Dependency between namespaces
# Test Number: 1.3
# Test Description:
#   - Apps in cluster-1 can only see frontend app in cluster-2
##################################################
apiVersion: networking.mesh.gloo.solo.io/v1
kind: VirtualMesh
metadata:
  name: virtual-mesh
  namespace: gloo-mesh
spec:
  federation:
    selectors:
      - { }
  meshes:
    - name: istiod-istio-system-cluster-2
      namespace: gloo-mesh
    - name: istiod-istio-system-cluster-1
      namespace: gloo-mesh
---
apiVersion: networking.enterprise.mesh.gloo.solo.io/v1beta1
kind: ServiceDependency
metadata:
  name: frontend
  namespace: gloo-mesh
spec:
  sourceSelectors:                       # all frontend labeled application have access to istio-system
  - kubeWorkloadMatcher:
      namespaces:
      - app
      clusters:
        - cluster-1
  destinationSelectors:
  - kubeWorkloadMatcher:
      labels:
        app: frontend
      namespaces:
      - app
      clusters:
      - cluster-2