apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: users-rest-api
  name: users-rest-api
  namespace: default
spec:
  selector:
    matchLabels:
      app: users-rest-api
  replicas: 1
  template:
    metadata:
      labels:
        app: users-rest-api
    spec:
      containers:
      - image: gcr.io/solo-public/docs/users-rest-api:latest
        name: users-rest-api
        ports:
        - containerPort: 5000
          name: http
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    gloo.solo.io/scrape-openapi-source: /swagger.json
    gloo.solo.io/scrape-openapi-retry-delay: "5s"
    gloo.solo.io/scrape-openapi-pull-attempts: "3"
    gloo.solo.io/scrape-openapi-use-backoff: "true"
  name: users-rest-api
  namespace: default
  labels:
    app: users-rest-api
spec:
  ports:
  - port: 5000
    protocol: TCP
  selector:
    app: users-rest-api