##################################################
# Test Name: Label Selector Based Route Selection
# Test Number: 8.2
# API Version: 2
# Test Description:
#   - Delegate cluster1.solo.io to cluster1 RouteTable
#   - Delegate cluster2.solo.io to cluster2 RouteTable
##################################################
apiVersion: admin.gloo.solo.io/v2
kind: RootTrustPolicy
metadata:
  name: auto-mtls
  namespace: gloo-mesh
spec:
  applyToMeshes:
    - name: istiod-istio-system-cluster1
      namespace: gloo-mesh
    - name: istiod-istio-system-cluster2
      namespace: gloo-mesh
  config:
    rootCertificateAuthority:            # auto generate ca certificates for each istio mesh
      generated:  {}
---
apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: admin                           # workspace for admin config
  namespace: gloo-mesh
spec:
  workloadClusters:
   - selector:
      namespaces:
        - name: istio-system
---
apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: admin-settings
  namespace: admin                       # workspace settings must exist in workspace namespace
spec:
 imports:                                # import setting from cluster1 and cluster2 
 - name: cluster1
 - name: cluster2
 exportTo:                               # export to cluster1 cluster2 so they can use ingressgateway
 - name: cluster1
 - name: cluster2
---
apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: cluster1                        # workspace for cluster1 config
  namespace: gloo-mesh
spec:
  workloadClusters:
   - name: cluster1
---
apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: cluster1-settings
  namespace: cluster1                   # workspace settings must exist in workspace namespace
spec:
 exportTo:                               # export to admin workspace
 - name: admin
---
apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: cluster2                        # workspace for cluster2 config
  namespace: gloo-mesh
spec:
  workloadClusters:
   - name: cluster2
---
apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: cluster2-settings
  namespace: cluster2                   # workspace settings must exist in workspace namespace
spec:
 exportTo:                               # export to admin workspace
 - name: admin
---
apiVersion: networking.gloo.solo.io/v2   # virtual gateway owned by admin workspace
kind: VirtualGateway
metadata:
  name: ingress                          # applies to all gateways in the mesh 
  namespace: admin
spec:
  listeners:
    - port:
        name: http2                      # apply configuration to ingress gateways http port
---
apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: cluster1-routes
  namespace: admin
spec:
  hosts:
    - 'cluster1.solo.io'
  virtualGateways:
    - name: ingress
  http:
  - name: cluster1-routes
    delegate:                            # delegate cluster1.solo.io to route tables with label cluster=cluster1
      routeTables:
      - selector:
          cluster: cluster1
---
apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: cluster2-routes
  namespace: admin
spec:
  hosts:
    - 'cluster2.solo.io'
  virtualGateways:
    - name: ingress
  http:
  - name: cluster2-routes
    delegate:                            # delegate cluster2.solo.io to route tables with label cluster=cluster2
      routeTables:
      - selector:
          cluster: cluster2
---
apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: frontend
  namespace: cluster1
  labels:
    cluster: cluster1
spec:
  hosts:
    - 'cluster1.solo.io'
  virtualGateways:
    - name: ingress
      workspace: admin
  http:
  - name: frontend
    forwardTo:
      destinations:
      - name: frontend
        namespace: app
        port:
          number: 8080
---
apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: frontend
  namespace: cluster2
  labels:
    cluster: cluster2
spec:
  hosts:
    - 'cluster2.solo.io'
  virtualGateways:
    - name: ingress
      workspace: admin
  http:
  - name: frontend
    forwardTo:
      destinations:
      - name: frontend
        namespace: app
        port:
          number: 8080