##################################################
# Test Name: Traffic Policy CSRF
# Test Number: 13.1
# Test Description:
#   - Enable CSRF policies will be evaluated, tracked and enforced.
##################################################
apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: global                           # workspace contains all connected services
  namespace: gloo-mesh
spec:
  workloadClusters:                      # select all clusters and namespaces
  - name: "*"
    namespaces:
    - name: "*"
---
apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: settings
  namespace: global
spec:
 {}
---
apiVersion: security.policy.gloo.solo.io/v2
kind: CSRFPolicy
metadata:
  name: csrf
  namespace: global
spec:
  applyToDestinations:
    - selector:
        labels:
          app: frontend
  config:
    filterEnabled: true    # Specifies that CSRF policies will be evaluated, tracked and enforced.
---