##################################################
# Test Name: Traffic Policy CSRF
# Test Number: 13.2
# Test Description:
#   - Specifies that CSRF policies will be evaluated, tracked but not enforced.
##################################################
apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: global                           # workspace contains all connected services
  namespace: gloo-mesh
spec:
  workloadClusters:                      # select all clusters and namespaces
  - name: "*"
    namespaces:
    - name: "*"
---
apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: settings
  namespace: global
spec:
 {}
---
apiVersion: security.policy.gloo.solo.io/v2
kind: CSRFPolicy
metadata:
  name: csrf
  namespace: global
spec:
  applyToDestinations:
    - selector:
        labels:
          app: frontend
  config:
    filterEnabled: false
    shadowEnabled: true
    percentage: 50
    additionalOrigins:
    - exact: frontend.solo.io
    - exact: frontend.app.svc.cluster.local
    - exact: login.solo.io