##################################################
# Test Name: Traffic Policy CSRF
# Test Number: 13.2
# Test Description:
#   - Specifies that CSRF policies will be evaluated, tracked but not enforced.
##################################################
apiVersion: networking.mesh.gloo.solo.io/v1
kind: VirtualMesh
metadata:
  name: virtual-mesh
  namespace: gloo-mesh
spec:
  federation:
    selectors:
      - { }
  meshes:
    - name: istiod-istio-system-cluster-2
      namespace: gloo-mesh
    - name: istiod-istio-system-cluster-1
      namespace: gloo-mesh
---
apiVersion: networking.mesh.gloo.solo.io/v1
kind: TrafficPolicy
metadata:
  namespace: gloo-mesh
  name: frontend
spec:
  # sourceSelector:                      # source selector omitted means "apply to anything calling destination"
  destinationSelector:
    - kubeServiceMatcher:                # kubeServiceMatcher is a select many services by labels/namespaces/clusters using AND notation
        labels:
          app: frontend                  # applications with app=frontend label
  policy:
    csrf:
      filterEnabled: false
      shadowEnabled: true
      percentage: 50
      additionalOrigins:
      - exact: frontend.solo.io
      - exact: frontend.app.svc.cluster.local
      - exact: login.solo.io