##################################################
# Test Name: HTTPS TLS Termination
# Test Number: 2.2
# API Version: 2
# Test Description:
#   - Terminate TLS at the ingress gateway using kubernetes mounted tls secret
#   - Requires tls certificate secret in every cluster with ingressgateway selected
##################################################
apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: global                           # workspace contains all connected services
  namespace: gloo-mesh
spec:
  workloadClusters:                      # select all clusters and namespaces
    - name: "*"
---
apiVersion: admin.gloo.solo.io/v2
kind: RootTrustPolicy
metadata:
  name: auto-mtls
  namespace: gloo-mesh
spec:
  applyToMeshes:
    - name: istiod-istio-system-cluster-1
      namespace: gloo-mesh
    - name: istiod-istio-system-cluster-2
      namespace: gloo-mesh
  config:
    rootCertificateAuthority:            # auto generate ca certificates for each istio mesh
      generated:  {}
---
apiVersion: networking.gloo.solo.io/v2
kind: VirtualGateway
metadata:
  name: ingress
  namespace: global
spec:
  listeners:
    - port:
        name: https                      # apply to the https port
      tlsSettings:                       # enable tls termination
        tls:
          certificates:                  # load TLS certificate secret from the gateway namespace 
            secretName: frontend-cert
          mode: SIMPLE                   # Simple TLS
---
apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: frontend
  namespace: global
spec:
  hosts:
    - '*'
  virtualGateways:
    - name: ingress
  http:
  - name: frontend
    forwardTo:
      destinations:
      - name: frontend
        namespace: app
        port:
          number: 8080