##################################################
# Test Name: Remove Route Request Header
# Test Number: 5.11.2
# Test Description:
#   - Remove request header on requests meant for frontend
# Issues
# - https://github.com/solo-io/gloo-mesh-enterprise/issues/3004
##################################################
apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: global                           # workspace contains all connected services
  namespace: gloo-mesh
spec:
  workloadClusters:                      # select all clusters and namespaces
  - name: "*"
    namespaces:
    - name: "*"
---
apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: settings
  namespace: global
spec:
 {}
---
# establish a listener on the ingress gateway
apiVersion: networking.gloo.solo.io/v2
kind: VirtualGateway
metadata:
  name: ingress
  namespace: global
spec:
  workloads:
    - selector:
        istio: ingressgateway
  listeners:
    - port:
        number: 80
      http: {}
---
apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: frontend
  namespace: global
spec:
  hosts:
    - 'api.solo.io'
  virtualGateways:
    - name: ingress
  http:
  - forwardTo:
      destinations:
      - ref:
          name: frontend
          namespace: {{.EchoContext.AppNamespace.Name}}
          cluster: cluster-1
        port:
          number: 8090
    options:
      headerManipulation:
        removeRequestHeaders:
          - User-Agent